name: Update DDNS

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  Update_DDNS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update DDNS
      run: bash cf_ddns.sh
      env:
        CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        CLOUDFLARE_ACCOUNT_EMAIL: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_LOCATION_ID: ${{ secrets.CLOUDFLARE_LOCATION_ID }}
        CLOUDFLARE_LOCATION_NAME: ${{ secrets.CLOUDFLARE_LOCATION_NAME }}
        DDNS_HOSTNAME: ${{ secrets.DDNS_HOSTNAME }}
    - uses: gautamkrishnar/keepalive-workflow@v1
